#!/usr/bin/python
import sys
import argparse
import afal

parser = argparse.ArgumentParser("Cancel debts between specified characters and the rest of the party")
parser.add_argument("--verbose", "-v", help="print progress messages", action='store_true', default=False)
parser.add_argument("date", help="When the debt-cancelling happened")
parser.add_argument("name", help="Character(s) whose debts will be cancelled", nargs='+')
args = parser.parse_args()

date = afal.str_to_date(args.date)
for char in args.name :

    try :
        char_id = int ( char )
        char_name = afal.get_char_name(char_id)

    except :
        char_id = afal.get_char_id(char)
        char_name = char

    payable = afal.get_char_payable(char_id)
    if len(payable) == 0:
        continue
    journal_id = afal.journal(date, char_id, None, 0,
 char_name + " cancelled debts")
    found = False
    for i in payable:
        if i['to_id'] == char_id:
            i['from_name'] = char_name
            i['to_name'] = char_name
            i['date'] = date
            i['part_of'] = journal_id
            afal.delete_debt(i, ' self-cancelled ')
            found = True
    receivable = afal.get_char_receivable(char_id)
    if found:
        payable = afal.get_char_payable(char_id)
    if len(payable) == 0 or len(receivable) == 0:
        continue

    for i in payable:
        i['date'] = date
        i['from_name'] = char_name
        i['part_of'] = journal_id
    for i in receivable:
        i['date'] = date
        i['to_name'] = char_name
        i['part_of'] = journal_id
# payable holds a list of of who we owe money to, sorted by who we owe it to
# receivable holds a list of who owes us money, sorted by who they are
    pay_start = 0
    rec_start = 0
    while pay_start < len(payable) and rec_start < len(receivable) :
        if payable[pay_start]['to_id'] < receivable[rec_start]['from_id'] :
            pay_start += 1
            continue
        if receivable[rec_start]['from_id'] < payable[pay_start]['to_id'] :
            rec_start += 1
            continue

# When we get here we've found a pair of debts to/from the same person
# Now figure out how many debts of each type we have with that person
        pay_id = payable[pay_start]['to_id']
        pay_order = payable[pay_start]['order']
        pay_end = pay_start
        while pay_end < len(payable) - 1 :
            if payable[pay_end+1]['to_id'] != pay_id or payable[pay_end+1]['order'] != pay_order :
                break
            pay_end += 1
        pay_cp = 0
        for i in range(pay_start,pay_end+1) :
            pay_cp += payable[i]['amount']

        rec_id = receivable[rec_start]['from_id']
        if rec_id != pay_id :
            print "rec and pay ids don't match",rec_id, pay_id, char_id
            sys.exit(1)
        rec_order = receivable[rec_start]['order']
        rec_end = rec_start
        while rec_end < len(receivable) - 1 :
            if receivable[rec_end+1]['from_id'] != rec_id or receivable[rec_end+1]['order'] != rec_order :
                    break
            rec_end += 1
        rec_cp = 0
        for i in range(rec_start,rec_end+1) :
            rec_cp += receivable[i]['amount']

# ok, figure out the total debt to be cancelled
        if pay_cp < rec_cp :
            cancel_cp = pay_cp
        else :
            cancel_cp = rec_cp
        pay_name = afal.get_char_name(pay_id)
        if args.verbose :
            print char_name, pay_name, pay_cp, rec_cp
        if cancel_cp == pay_cp :
            for i in range(pay_start,pay_end+1) :
                afal.delete_debt(payable[i], ' completely cancelled ')
            pay_start = pay_end + 1
        else :
# modify all the payable debts appropiaately
            pay_cancel_cp = cancel_cp
            for i in range ( pay_start, pay_end + 1 ) :
                cur_cp = payable[i]['amount']
                cxl_cp = afal.divide_cp(pay_cancel_cp * cur_cp, pay_cp)
                if args.verbose :
                    print char_name,"to",pay_name,"was",cur_cp,"cxl",cxl_cp
                if cur_cp == cxl_cp:
                    afal.delete_debt(payable[i], ' completely cancelled ')
                else:
                    afal.debt_lower_owed(payable[i], cxl_cp, ' cancelled ')
		pay_cancel_cp -= cxl_cp
		pay_cp -= payable[i]['amount']
        if cancel_cp == rec_cp :
            for i in range(rec_start,rec_end+1) :
                cp = receivable[i]['amount']
                afal.delete_debt(receivable[i], ' completely cancelled ')
            rec_start = rec_end + 1
        else :
# modify all the receivable debts appropriately
            rec_cancel_cp = cancel_cp
            for i in range ( rec_start, rec_end + 1 ) :
                cur_cp = receivable[i]['amount']
                cxl_cp = afal.divide_cp(rec_cancel_cp * cur_cp, rec_cp)
                if args.verbose :
                    print pay_name,"to",char_name,"was",cur_cp,"cxl",cxl_cp
                if cur_cp == cxl_cp:
                    afal.delete_debt(receivable[i], ' completely cancelled ')
                else:
                    afal.debt_lower_owed(receivable[i], cxl_cp, ' cancelled ')
                rec_cancel_cp -= cxl_cp
                rec_cp -= receivable[i]['amount']
afal.fini()
