#!/usr/bin/python
from __future__ import print_function
import afal_config
import afal
import cgi
import cgitb
import os

cgitb.enable()
date = afal.date_to_str(afal.get_journal_dates()[-1])
characters = afal.get_characters('Current')
characters.insert(0,'party')
if afal_config.text:
    header = 'Cash Summary as of {date}'
    line = '{char:10} {v:14} {c}'
    trailer = ''
else:
    header = \
 'Content-Type: text/html\n'\
 '\n'\
 '<html>\n'\
 ' <head><title>AFAL Cash Summary</title></head>\n'\
 ' <body background="{background}">\n'\
 '  {menu_html}\n'\
 '  <center><h1>Anything For A Laugh</h1>\n'\
 '   <h2>Cash in hand as of {date}</h2>\n'\
 '   <a href="{menu_url}"><b>Return to Menu</b></a><br>\n'\
 '  </center><br>\n'\
 '  <table border="1"><tr><th>Character</th><th>Total</th><th>'\
 'Coins</th></tr>'
    line = \
 '   <tr><td><a href="{report}?char={char}&generate=Character">' \
 '{char}</a></td><td>{v}</td><td>{c}</td></tr>'
    trailer = \
 '  </table>\n'\
 '  <br><center><a href="{menu_url}"><b>Return to Menu</b></a></center>\n'\
 ' </body>\n'\
 '</html>\n'

print(header.format(menu_html = afal.menu_html, menu_url = afal_config.menu_url,
 background = afal_config.background, date = date))
for char in characters:
    m = afal.get_char_money(char)
    value_cp = 0
    coins = ''
    pre = ''
    npre = ', '
    for i in m:
        value_cp += i['quantity'] * i['copper_equiv']
        if i['abbrev']:
            text = i['abbrev']
        else:
            text = i['coin']
        coins += '{p}{n} {t}'.format(p=pre, n=i['quantity'], t=text)
        pre = npre

    if value_cp > 0:
        print(line.format(
 char = char, v = afal.cp_to_str(value_cp), c = coins, report = afal_config.report))
print(trailer.format(menu_url=afal_config.menu_url))
afal.fini()
