#!/usr/bin/python
from __future__ import print_function
import argparse
import cgitb
import afal_config
import afal

cgitb.enable()
date = afal.date_list[-1]
afal.character_list.insert(0,afal.party)
if afal_config.text:
    parser = argparse.ArgumentParser('Generate a cash summary')
    parser.add_argument('--width', '-w', type=int, default=130, help='width to wrap at')
    args = parser.parse_args()
    header = 'Cash Summary as of {date}'.format(date = date)
    line = '{char:10} {v:14} {c}'
    footer = ''
    wmax = args.width
else:
    header = \
 afal.html_header('AFAL Cash Summary')+\
 '   <h1>Anything For A Laugh</h1>\n'\
 '   <h2>Cash in hand as of {date}</h2><br>\n'\
 '   <table border="1"><tr><th>Character</th><th>Total</th><th>'\
 'Coins</th></tr>'.format(date = date)
    line = \
 '    <tr><td><a href="{report_url}?todo=char.{char}">' \
 '{char}</a></td><td>{v}</td><td>{c}</td></tr>'
    footer = \
 '   </table>\n' + afal.html_footer()
    wmax = None

afal.pw(header, max=wmax, indent=4)
for char in afal.character_list:
    m = afal.get_char_money(char)
    value_cp = 0
    coins = ''
    pre = ''
    npre = ', '
    for i in m:
        n=i['quantity']
        value_cp += n * i['copper_equiv']
        if 'abbrev' in i:
            text = i['abbrev']
        elif n == 1:
            text = i['coin'].format(s = '', es = '', y = 'y')
        else:
            text = i['coin'].format(s = 's', es = 'es', y = 'ies')
        coins += '{p}{n} {t}'.format(p=pre, n=n, t=text)
        pre = npre

    if value_cp > 0:
        afal.pw(line.format(
 char = char, v = afal.cp_to_str(value_cp), c = coins, report_url = afal_config.report_url), max = wmax, indent=4)
afal.pw(footer, max = wmax, indent = 4)
afal.fini()
