#!/usr/bin/python
from __future__ import print_function
import argparse
import cgitb
import afal_config
import afal

cgitb.enable()
date = afal.date_list[-1]
afal.character_list.insert(0,afal.party)
if afal_config.text:
    parser = argparse.ArgumentParser('Generate a cash summary')
    parser.add_argument('--width', '-w', type=int, default=130, help='width to wrap at')
    args = parser.parse_args()
    header = 'Cash Summary as of {date}'
    line = '{char:10} {v:14} {c}'
    trailer = ''
    wmax = args.width
else:
    header = \
 'Content-Type: text/html\n'\
 '\n'\
 '<html>\n'\
 ' <head><title>AFAL Cash Summary</title></head>\n'\
 ' <body background="{background}">\n'\
 '  {menu_html}\n'\
 '  <center><h1>Anything For A Laugh</h1>\n'\
 '   <h2>Cash in hand as of {date}</h2>\n'\
 '   <a href="{menu_url}"><b>Return to Menu</b></a><br>\n'\
 '  </center><br>\n'\
 '  <table border="1"><tr><th>Character</th><th>Total</th><th>'\
 'Coins</th></tr>'
    line = \
 '   <tr><td><a href="{report}?todo=char.{char}">' \
 '{char}</a></td><td>{v}</td><td>{c}</td></tr>'
    trailer = \
 '  </table>\n'\
 '  <br><center><a href="{menu_url}"><b>Return to Menu</b></a></center>\n'\
 ' </body>\n'\
 '</html>\n'
    wmax = None

afal.pw(header.format(menu_html = afal.menu_html, menu_url = afal_config.menu_url,
 background = afal_config.background, date = date), max=wmax, indent=4)
for char in afal.character_list:
    m = afal.get_char_money(char)
    value_cp = 0
    coins = ''
    pre = ''
    npre = ', '
    for i in m:
        n=i['quantity']
        value_cp += n * i['copper_equiv']
        if 'abbrev' in i:
            text = i['abbrev']
        elif n == 1:
            text = i['coin'].format(s='', es='')
        else:
            text = i['coin'].format(s='s', es='es')
        coins += '{p}{n} {t}'.format(p=pre, n=n, t=text)
        pre = npre

    if value_cp > 0:
        afal.pw(line.format(
 char = char, v = afal.cp_to_str(value_cp), c = coins, report = afal_config.report), max = wmax, indent=4)
afal.pw(trailer.format(menu_url = afal_config.menu_url), max = wmax, indent = 4)
afal.fini()
