#!/usr/bin/python
import argparse
import afal

parser = argparse.ArgumentParser("Add one or more characters to the database")
parser.add_argument("--gold", "-g", type=float, help="starting gold pieces", default=0)
parser.add_argument("--copper", "-c", type=float, help="starting copper pieces", default=0)
parser.add_argument("--verbose", "-v", help="print progress messages", action='store_true', default=False)
parser.add_argument("name", help="The name of the character to add", nargs='+')
args = parser.parse_args()
for name in args.name :
    afal.insert_char(name, afal.gp_cp_to_cp(args.gold, args.copper))
    if args.verbose :
        print name, "added as", afal.get_char_id(name)
afal.fini()
