#!/usr/bin/python
import sys
import subprocess
import argparse
import afal

parser = argparse.ArgumentParser('Insert an item into the database')
parser.add_argument("item", help="Item Name")
parser.add_argument("party", help="Party that acquired the item")
parser.add_argument("owner", help="The character that owns/holds the item", nargs='?', default = None)
parser.add_argument("date", help="Date the item was sold to the owner on", nargs='?',default = None)
parser.add_argument("--note", "-n", help="Note to add to the item", default = None)
parser.add_argument("--verbose", "-v", help="print progress messages", action='store_true', default=False)
parser.add_argument("--cash","-c",type=float, help="Cash amount the item was sold for", nargs='?', default = 0)
parser.add_argument("--debt","-d",type=float, help="Debt amount the item was sold for", nargs='?', default = 0)
args=parser.parse_args()
try :
    party_id = afal.get_party_id(args.party)

except :
    party_id = int(args.party)
    party_name = afal.get_party_name(party_id)

if args.owner == None :
    owner_id = None
    owner_name = 'Party'
else :
    try :
        owner_id = afal.get_char_id(args.owner)

    except :
        try :
            owner_id = int(args.owner)
            owner_name = afal.get_char_name(owner_id)

        except :
            print "Unknown owner", args.owner
            sys.exit(1)

if args.date != None :
    item_id = afal.insert_item(args.item, party_id, note=args.note)
    if args.verbose :
        print "Item", args.item, "added as #", item_id
    afal.fini()
    result = subprocess.check_output(["buy", args.date, str(item_id), args.owner, "-c", str(args.cash), "-d", str(args.debt)])
    if args.verbose :
       print "Item", item_id, "sold to", args.owner, "with result", result
    sys.exit(0)

item_id = afal.insert_item(args.item, party_id, owner_id=owner_id, note=args.note)
if args.verbose :
    print "Item", args.item, "added as #", item_id
afal.fini()
