#!/usr/bin/python
from __future__ import print_function
import afal_config
import afal
import cgi
import cgitb
import os
import sys

cgitb.enable()

form = cgi.FieldStorage()
todo = form.getfirst('todo')
if todo is None or todo == '' or '.' not in todo:
        os.execv('./menu', sys.argv)
(cl, inst) = todo.split('.', 1)
if cl != 'map':
        os.execv('./menu', sys.argv)
map_of = inst
map_name = afal._map_to_name(map_of)
title = 'AFAL map of ' + map_name

print('''{hdr}
   <h1>{map_name}</h1>
   <object style="background:white" width="100%" height="86%" data="../maps/{map_of}" type="image/svg+xml">Map Goes Here</object>
{ftr}'''.format(hdr = afal.html_header(title), map_name = map_name, map_of = map_of, ftr = afal.html_footer()))
