#!/usr/bin/python
from __future__ import print_function
import afal_config
import afal
import cgi
import cgitb

cgitb.enable()


print(
 afal.html_header.format(title = 'AFAL Report Menu', add_menu = '')
 + '  </center>\n'
 + ' </body>\n'
 + '</html>\n'
)
