#!/usr/bin/python
# This can be used as either a cgi program or from the command line
from __future__ import print_function
import afal_config
import afal
import cgi
import cgitb

cgitb.enable()

title = 'AFAL Report Menu'
print(
 'Content-Type: text/html\n'
 '\n'
 '<html>\n'
 ' <head><title>{title}</title></head>\n'
 ' <body background="{background}">\n'
 ' {menu_html}\n'
 ' </body>\n'
 '</html>\n'.format(
 title = title,
 menu_html = afal.menu_html,
 background = afal_config.background,
))
