#!/usr/bin/python
import argparse
import afal

def create_parties(d):
#    p_id = afal.insert_party(d['party'],afal.str_to_date(d['date']))
    p_id = 1
    if args.verbose:
        print "created party",d['party'], "date", d['date'], "with id #", p_id
    for i in d.keys():
        if i == 'party' or i == 'date':
            continue
#        afal.insert_char_party(afal.get_char_id(i),p_id, d[i])
        if args.verbose:
            print "added character",i, "to party with share",d[i]

parser = argparse.ArgumentParser("Create parties from parties.dat")
parser.add_argument("--verbose", "-v", help="print progress messages", action='store_true', default=False)
parser.add_argument("--file", "-f", help="file to read", default='parties.dat')
args = parser.parse_args()

file = open(args.file)
afal.parse_file(file, create_parties, dict())
afal.fini()
