#!/usr/bin/python
# Usage: addparty {party name} ( {char} {share} ) ...
import argparse
import afal

parser = argparse.ArgumentParser("Create a party or add characters to a party")
parser.add_argument("--verbose", "-v", help="print progress messages", action='store_true', default=False)
parser.add_argument("party", help="Party to create")
parser.add_argument("char", help="character(s) and share(s) to add", nargs='*')
args = parser.parse_args()

party = args.party
try :
    party_id = int(party)
    party_name = afal.get_party_name(party_id)
except :
    try :
        party_id = afal.insert_party(party)
        party_name = party
    except :
        party_id = afal.get_party_id(party)
        party_name = party

while len(args.char) > 0 :
    char_name = args.char.pop(0)
    share = args.char.pop(0)
    try :
        char_id = afal.get_char_id(char_name)
    except :
        char_id = int(char_name)
    afal.insert_char_party(char_id, party_id, share)

afal.fini()
